import assert from 'node:assert/strict'
import { test } from 'node:test'
import { nativeFixture, post } from '../../dsh-excel-understanding/test/native-fixture.js'
import { mockMcheResponse } from './model-fixture.js'

test('真实DSH翅片工具、双部件用户确认、追问、换型和重启恢复', { timeout: 90000 }, async t => {
  const f = await nativeFixture(t, false, { respond: mockMcheResponse })
  const asset = await fetch(f.base + '/mche-fins.js')
  assert.equal(200, asset.status)
  assert.match(await asset.text(), /finSelectionPane/)
  const reply = await post(f, '/api/chat', { prompt: '翅片验收：扁管选A01S，翅片主表宽16mm、焊后高8.1mm、片距1.4mm；管长500mm、管数20、管间距10mm。' })
  assert.equal(6, reply.details.filter(d => d.mche).length)
  assert.ok(reply.details.some(d => d.mche?.view === 'selection' && d.mche.component === 'fin' && d.status === 'completed'))
  const sessionId = reply.sessionId, request = (path, extra = {}, status = 200) => post(f, `/api/mche/${path}`, { sessionId, ...extra }, status)
  let state = await request('case')
  assert.equal('draft', state.finCandidates.basis)
  assert.deepEqual({}, state.confirmed)
  const tubeProposal = state.proposals.find(p => p.component === 'tube').id, finProposal = state.proposals.find(p => p.component === 'fin').id
  state = await request('confirm-inputs', { revision: state.revision, reviewId: state.inputReviewId, fields: Object.keys(state.draft) })
  state = await request('confirm-tube', { revision: state.revision, proposalId: tubeProposal })
  const finRequest = { revision: state.revision, proposalId: finProposal }
  state = await request('confirm-fin', finRequest)
  await request('confirm-fin', finRequest, 409)
  assert.equal(true, state.status.tubeConfirmed)
  assert.equal(true, state.status.finConfirmed)
  await post(f, '/api/chat', { sessionId, prompt: '翅片追问：查看当前选择与参数准备。' })
  state = await request('case')
  assert.equal(true, state.status.tubeParametersComplete)
  assert.equal(true, state.status.finParametersComplete)
  assert.equal(false, state.status.parametersComplete)
  assert.equal(false, state.status.refrigerantConfirmed)
  assert.equal(false, state.preparation.calculationReady)
  assert.equal(0.016, state.preparation.parameters.finGeometry.width.value)
  assert.ok(JSON.stringify(f.received.at(-1).messages).includes('snapshotId'))
  const beforeRestart = structuredClone(state)
  await f.close(); await f.boot()
  assert.deepEqual(beforeRestart, await request('case'))
  const opened = await post(f, '/api/session/open', { sessionId })
  assert.ok(opened.messages.some(m => m.details?.some(d => d.mche?.component === 'fin' && d.mche?.proposalId === finProposal)))
  await post(f, '/api/chat', { sessionId, prompt: '修改翅片：片距改为1.2mm，比较B01和B02。' })
  state = await request('case')
  assert.equal(true, state.status.tubeConfirmed)
  assert.equal(false, state.status.finConfirmed)
  assert.equal('B02', state.proposals.at(-1).name)
  state = await request('confirm-fin', { revision: state.revision, proposalId: state.proposals.at(-1).id })
  assert.equal('B02', state.selections.fin.name)
  assert.equal('A01S', state.selections.tube.name)
})

test('表格产生翅片草稿、直接型号独立会话，保留局部无标题原值', { timeout: 60000 }, async t => {
  const f = await nativeFixture(t, false, { respond: mockMcheResponse })
  const reply = await post(f, '/api/chat', { prompt: '翅片表格：请按提供的尺寸创建草稿并比较。', tables: [{ title: '翅片条件', source: '用户粘贴',
    columns: ['参数', '值', '单位'], rows: [['翅片宽度', '16', 'mm'], ['焊后高度', '8.1', 'mm'], ['片距', '1.4', 'mm']] }] })
  const state = await post(f, '/api/mche/case', { sessionId: reply.sessionId })
  assert.equal(1.4, state.draft.finPitch.value)
  assert.deepEqual({}, state.confirmed)
  assert.match(JSON.stringify(f.received[0].messages), /用户粘贴/)
  const direct = await post(f, '/api/chat', { prompt: '直接翅片：请查询B150L并建议选择。' })
  assert.notEqual(reply.sessionId, direct.sessionId)
  const record = await post(f, '/api/mche/fin', { sessionId: direct.sessionId, name: 'B150L' })
  assert.equal(1.16, record.fin.unclassified.sourceColumnM)
  const other = await post(f, '/api/mche/case', { sessionId: direct.sessionId })
  assert.deepEqual({}, other.draft)
  await post(f, '/api/mche/confirm-fin', { sessionId: direct.sessionId, revision: other.revision, proposalId: state.proposals.at(-1).id }, 409)
})
